### ISSUE TITLE
TODO Functionalities to implement

### ISSUE THREAD

**Issue by marcoplacenti** [marcoplacenti/MLPipe#3]
- [ ] HP Tuning
- [ ] Dataset Versioning (W&B? DVC? Others?)
- [ ] Model Versioning (Model Registry?)
- [ ] Artefacts Storage (Related to the two above)
- [ ] Better Logging
- [ ] Enable reading from S3 (NN Corporate)
- [ ] Distributed learning (Pytorch Lightning?)
- [ ] Model Deployment & Serving
- [ ] Model Monitoring and CT

**Comment by marcoplacenti** [comment]
HP Tuning: Currently experimenting with Ray Tune. Many issues encountered, can't get it to work.

Dataset and Model Versioning + Better logging: probably will go for W&B due to possibility to centralise resources. Other tools may be better at specific tasks but makes integration more complex.

Model Deployment/Serving/Monitoring/CT: Potential solutions are BentoML, CorteX, some AWS resources. Still to explore.
